global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'mi-backend-java'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [
        'host.docker.internal:8080',  # Agregador
        'host.docker.internal:8081',  # Fuente Dinámica
        'host.docker.internal:8082',  # Fuente Estática
        'host.docker.internal:8083',  # Proxy
        'host.docker.internal:8089'   # Estadisticas
      ]